### ISSUE TITLE
byte compiler warning: functions are not known to be defined:     json-pretty-print, json-mode

### ISSUE THREAD

**Issue by xuchunyang** [abrochard/walkman#11]
I just installed walkman via M-x package-install and encountered this warning:
 
```
walkman.el:365:1:Warning: the following functions are not known to be defined:
    json-pretty-print, json-mode
```

`json-pretty-print` is from `json.el` so it needs to be loaded. and `json-mode` is provied by a third party package json-mode, which is not avaliable if user does not installed by themself.

**Comment by abrochard** [comment]
Thank you for reporting this! This is related to the last PR merged. I'm working on a fix right now and I will also setup automated builds to catch that in the future.

**Comment by abrochard** [comment]
Should now be fixed as part of https://github.com/abrochard/walkman/pull/12.
