### ISSUE TITLE
Add support for multi-part file uploads

### ISSUE THREAD

**Issue by dcaixinha** [abrochard/walkman#2]
Hey @abrochard, first of all thank you for this really cool package :raised_hands: (and I'm also a fan of `kubel` :smile:)

I have to interact with a lot of APIs that require the upload of files through multi-part. Is that something that's easy / feasible to add in this library? I didn't study it yet, and I don't know the backend for making the requests, but I can try to provider some cURL examples of what I'd like to have.

Thanks again :bowing_man:

**Comment by abrochard** [comment]
Hi @dcaixinha , thank you so much! It means a lot.

I'm not familiar at with multi-part upload. I don't think it's currently possible but if you share what you have in mind I can take a look!

**Comment by dcaixinha** [comment]
Hey @abrochard, below is an example of a multi-part upload with `curl`:
```
 curl https://some-api/some-endpoint \
  -F 'type=document' \
  -F 'file=@/home/dcaixinha/sample_document.jpg;type=image/jpg'
```
The `type=document` bit is just an example of metadata you may want to pass on the multi-part request. This is the usual way to upload files against an API – where the file itself is encoded under the `file` key. `curl` will then take care of encoding this request with the proper `multi-part` boundaries. Do you think it's feasible to add something this to `walkman`? :pray:

**Comment by abrochard** [comment]
I see. That's pretty handy.
It's definitely possible to support that in theory, in practice the hard question is how should that look in terms of org syntax?

```org
* Sample multi-part
  POST https://some-api/some-endpoint
  ???? [[file:/home/dcaixinha/sample_document.jpg]]
```

Do you have a preference?

**Comment by dcaixinha** [comment]
Yeah, leveraging Org link syntax makes sense, but probably just for files. We'd also need to support other form fields – such as the `-F 'type=document'` in my example above.

There could be any number of them (and the `@` is only used for files). Given this can be an unbounded list of form parameters, it's probably better to have list like what we have for the headers? So something like:

```org
* Sample multi-part
  POST https://some-api/some-endpoint
  - type: document
  - file: [[/home/dcaixinha/sample_document.jpg]]
```

However, I don't know the best way to differentiate these from the actual headers... Any thoughts on that?

**Comment by abrochard** [comment]
My best idea right now is to use an org drawer?

```org
* Multi part
  POST https://httpbin.org/post
  ::form::
  - type: document
  - file: [[/home/dcaixinha/sample_document.jpg]]
  ::end::
```

every header in the drawer gets a `-F` and org links to file get an extra `@`.
What do you think?

**Comment by dcaixinha** [comment]
Yeah, that looks very good :heart_eyes: 

Just a note: [Org drawers](https://orgmode.org/manual/Drawers.html) are usually written with a single `:` surrounding them, and the name (and `:END:`) is usually uppercase.

**Comment by abrochard** [comment]
Sounds good! I will get started on this when I can. Thank you for your input.

**Comment by abrochard** [comment]
I did a first draft https://github.com/abrochard/walkman/pull/3

Could you check out the branch and possibly test with your use case?

One important point is that the form headers have to be after the regular headers.

Valid:
```
* Multi part
  POST https://httpbin.org/post
  - Accept: application/json
  :form:
  - type: document
  - file: [[/home/username/sample_document.jpg]]
  :end:
```
Invalid
```
* Multi part
  POST https://httpbin.org/post
  :form:
  - type: document
  - file: [[/home/username/sample_document.jpg]]
  :end:
  - Accept: application/json
```

**Comment by dcaixinha** [comment]
Hey @abrochard, sorry for the delay but was only able to test it this morning.

I've been testing the branch and it's working out great :raised_hands: :clap: just left a minor comment on the PR – otherwise this is looking good :+1:

**Comment by abrochard** [comment]
No worries at all!
I updated to `:FORM:` and pushed some more docs and tests. Going to merge soon. Let me know if you find any related bugs
