### ISSUE TITLE
How to set variable per file / heading?

### ISSUE THREAD

**Issue by dcaixinha** [abrochard/walkman#4]
Hey @abrochard, this isn't exactly a bug but more of a help request.

Before using `walkman` I used to use [File Variables](https://www.gnu.org/software/emacs/manual/html_node/emacs/Specifying-File-Variables.html#Specifying-File-Variables) to have a different file for staging and production API (setting the URLs and tokens with variables accordingly). I was trying to do the same with walkman but apparently the variable needs to be global. For example I would have a `staging.org` file with:
```Org
-*- walkman-api-url: "https://some-api"; walkman-api-token: "bogus_token" -*-

* Simple GET
  GET `walkman-api-url`/some-get-endpoint
  - Authorization: Bearer `walkman-api-token`
```
But then I get `Symbol's value as variable is void: walkman-api-url`. I was also thinking that the same could be achieved by having some sort of pre-request hook and then have all the environments in the same file. For example in `http.org` I would wave:
```Org
* Staging
** Simple GET
  <some hook to set `walkman-api-url` and `walkman-api-token`
  GET `walkman-api-url`/some-get-endpoint
  - Authorization: Bearer `walkman-api-token`
* Production
** Simple GET
  <some hook to set `walkman-api-url` and `walkman-api-token`
  GET `walkman-api-url`/some-get-endpoint
  - Authorization: Bearer `walkman-api-token`
```
Which one would you say is the best way @abrochard? Or would you do this differently? Thanks :bowing_man:

**Comment by abrochard** [comment]
That's pretty neat. I need to look into it.
One thing I'm confused about is why having separate files with the same requests but different environments? My intuition would be to do the opposite and have one file with all my requests, and instead find a nice way to change the variables to point to staging/prod/etc.

**Comment by abrochard** [comment]
FYI I just pushed https://github.com/abrochard/walkman/commit/1e06fee64555f627a72857b5706575297223a4cf which supports local variables out of the box and added an example in sample.org

```org
# -*- my-http-status: 400; -*-

* Embedded lisp variable
  GET https://httpbin.org/status/`my-http-status`
```

**Comment by dcaixinha** [comment]
Hey @abrochard, thank you for the speedy work on this :tada: :bowing_man:

I agree with you that having separate files isn't the best option. For future reference (and possible other folks that find this thread), this is the best I've achieved currently with `walkman`:
```org-mode
* Local
** Token
  #+begin_src emacs-lisp
    (setq my-token "local_token")
  #+end_src
* Development
** Token
  #+begin_src emacs-lisp
    (setq my-token "dev_token")
  #+end_src
* Production
** Token
  #+begin_src emacs-lisp
    (setq my-token "prod_token")
  #+end_src
* Some request
  POST http://some-url
  - Authorization: Bearer `my-token`
```
Then, whenever I want to make a request to a certain environment, I move the cursor to it and run `org-babel-execute-subtree`, and then proceed to making the requests :rocket: it's been working great!

**Comment by abrochard** [comment]
Amazing! Thank you for sharing
