### ISSUE TITLE
Callbacks don't work when FORM drawer is present

### ISSUE THREAD

**Issue by dcaixinha** [abrochard/walkman#5]
Hey @abrochard, it's me again :smile: 

Having the following snippet:
```
* Some request
  POST http://some-url
  - Authorization: Bearer `my-token`
  :FORM:
  - type: document
  - file: [[/home/dcaixinha/test_document.png]]
  :END:
  1. First callback
    #+begin_src emacs-lisp
      (lambda (status headers body)
        (message "status %s, headers %s, body %s" status headers body))
    #+end_src
```
I can't get the callback to run. I've copied it from the `sample.org` file, but it always errors with:
```
walkman--parse-response: Search failed: "^HTTP/[0-9]\\.?[0-9]? \\([0-9]\\{3\\}\\) \\([A-Z ]+\\)?"
```
If I remove the `:FORM` drawer from the request than everything works. I've tried looking at the function that's giving the error but couldn't figure out why having the drawer there yields an error. Can you help me out pleas? :pray:

**Comment by abrochard** [comment]
Thank you for reporting this. This is actually pretty tricky. I am hard at work finding a long term fix.

**Comment by abrochard** [comment]
I think I fixed it with https://github.com/abrochard/walkman/commit/d3862fd4302ba7b0194ae80d561cbb32c4cd8b1d which is a pretty big re-write of how org entries are parsed. Please give it a try and re-open if it's not fixed.

**Comment by dcaixinha** [comment]
Hey @abrochard, running the latest `walkman` (`20200403.1730`) and right now I get this error on every request, with or without callbacks present, and with or without `:FORM:` drawer present :confused: 
```
walkman--parse-response: Search failed: "^HTTP/[0-9]\\.?[0-9]? \\([0-9]\\{3\\}\\) \\([A-Z ]+\\)?"
```

**Comment by abrochard** [comment]
Oh boy. What did I break now

**Comment by abrochard** [comment]
Hmm. I restarted Emacs, update the package, and ran the first query in sample.org and I don't see any error. Did you restart? Can you share the failing query?

**Comment by dcaixinha** [comment]
I had restarted Emacs and the errors kept appearing – however, now I delete the package locally so that it would go to MELPA again and now I don't see the error! However, I still don't get the callbacks to work. I'm doing a get request to an API that returns an image:
```
* Get Image
  GET `api-url`/api/get_image
  - Authorization: Token token=`token`
  1. First Callback
  #+begin_src emacs-lisp
    (lambda (status headers body)
      (message "status %s, headers %s, body %s" status headers body))
  #+end_src
```
So, the callback is there but the only thing I see on the messages buffer is;
```
Response status code: 200
```
What am I doing incorrectly? :pray:

**Comment by abrochard** [comment]
From my digging, here is what I think it happening:
1. you need to indent properly your callback src block under your list for the org parser to pick it up
2. the org parser is not accepting a mixed between unordered and ordered list

```
- element
- unordered element
1. ordered element
```
^ this causes ordered element to not be picked up.

I am going to think about potential solution. In the meantime, I got your example working with an empty body separator

```
* Get Image
  GET `api-url`/api/get_image
  - Authorization: Token token=`token`
  #+begin_src json
  #+end_src
  1. First Callback
    #+begin_src emacs-lisp
      (lambda (status headers body)
        (message "status %s, headers %s, body %s" status headers body))
    #+end_src
```

**Comment by dcaixinha** [comment]
Just tested with the indented lambda and adding an empty `JSON` source block, and I only get the `Response status code: 200`. But I think your hypothesis is right, because when I was editing this buffer I noticed emacs was trying to auto-convert the callback to `- First callback` (i.e. turn it into an unordered element).

Would it be easier (to parse) if the callbacks where nested elements (i.e. `** First callback`)?

**Comment by abrochard** [comment]
It would be easier I suppose but I don't want to break backward compatibility. I am going to keep looking, worst case I may have a hacky fix

**Comment by dcaixinha** [comment]
Yeah, I understand. That would be something feasible if packages in Emacs followed [semantic versioning](https://semver.org/), as we could break the contract in a major release. Anyway, curious to know what the hacky fix is :nerd_face:

**Comment by dcaixinha** [comment]
Closing this issue since it's not happening anymore with the latest version. For future people searching for this, here's the format I have working for an HTTP request with a form and callback:
```org-mode
* Some upload with Form
  POST https://httpbin.org/post
  - Accept: application/json
  :FORM:
  - some_variable: some_value
  - file: [[/home/your_user/some_photo.png]]
  :END:
  1. Some callback
     #+BEGIN_SRC emacs-lisp
       (lambda (status headers body)
         (message "Hey I'm on the 1st callback")
     #+END_SRC
```
