### ISSUE TITLE
Add support to parse JSON output

### ISSUE THREAD

**Issue by dcaixinha** [abrochard/walkman#6]
Whenever I do a request that receives a huge JSON payload in the body, I have to copy it and format it in some other way to make it readable. Is there already some way to do this currently with `walkman`? The usual way to do this in cURL is piping it to some other tool (like `jq` or `json_pp`). Maybe `walkman` could support something similar (that would be configurable)? Thanks :pray:

**Comment by abrochard** [comment]
I got tricked because httpbin.org responses are already formatted.

There are few possible ways. Probably the easiest would be to run a hook in the response buffer and run `json-parse-buffer` on it.
