### ISSUE TITLE
Add support for async requests

### ISSUE THREAD

**Issue by dcaixinha** [abrochard/walkman#7]
Hey @abrochard,

I want to stop just asking for stuff and try to start contributing. I want to tackle something that you have in your TODO in the README: adding support for async requests. Do you already have an idea on how to accomplish this?

From my quick research there's two packages that might be interesting to look at:
* [emacs-async](https://github.com/jwiegley/emacs-async)
* [emacs-aio](https://github.com/skeeto/emacs-aio)

What's your opinion on the above? Thanks! :pray:

**Comment by abrochard** [comment]
ahah no worries. I'm pretty busy these days so not sure when I'll get to it but I have some ideas.

You want to be able to trigger a request and not have emacs hang right? In theory it should be as easy as switching https://github.com/abrochard/walkman/blob/master/walkman.el#L76 from `call-process` to `start-process` and update the args.
